name = "lista-super"
compatibility_date = "2024-03-20"
main = "worker.js"

[assets]
directory = "."
binding = "ASSETS"

[[kv_namespaces]]
binding = "SHOPPING_KV"
id = "13cc99b0dd0e4927a743ec453664ac02"
